esy_cache_key: &esy_cache_key
  key: esy-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

esy_post_build_cache_key: &esy_post_build_cache_key
  key: esy-post-build-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: sudo apt install rsync
      - run: sudo npm -g install esy@preview
      - restore_cache:
          <<: *esy_cache_key
      - restore_cache:
          <<: *esy_post_build_cache_key
      - run: esy install
      - save_cache:
          <<: *esy_cache_key
          paths:
            - ~/.esy
      - run: esy build
      - save_cache:
          <<: *esy_post_build_cache_key
          paths:
            - ~/.esy
      - run: esy jbuilder runtest --no-buffer
