variables:
  ESY__PREFIX: $(build.binariesDirectory)/.esy
  NPM_CONFIG_PREFIX: $(agent.homeDirectory)/.npm
jobs:
  - job: MacOS
    pool:
      vmImage: "macOS 10.13"
    steps:
      - script: |
          echo '##vso[task.prependpath]$(NPM_CONFIG_PREFIX)/bin'
        displayName: "Setup env"
      - script: npm -g install esy@latest
        displayName: "Install esy"
      - script: |
          esy install
        displayName: "Install dependencies"
      - script: |
          esy build:mac
        displayName: "Build"
      - script: |
          esy test core
        displayName: "Test core"
      - script: |
          esy test renderer_term
        displayName: "Test term renderer"
      - script: |
          esy test renderer_cocoa
        displayName: "Test cocoa renderer"
      - script: |
          esy bootstrap:mac
          esy test:mac
        displayName: "Compile and test BRTesterMac"
  - job: Linux
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - script: |
          echo '##vso[task.prependpath]$(NPM_CONFIG_PREFIX)/bin'
        displayName: "Setup env"
      - script: npm -g install esy@latest
        displayName: "Install esy"
      - script: |
          esy install
        displayName: "Install dependencies"
      - script: |
          esy build:linux
        displayName: "Build"
      - script: |
          esy test core
        displayName: "Test core"
      - script: |
          esy test renderer_term
        displayName: "Test term renderer"
